services:
  - type: web
    name: car-rental-system
    env: node
    rootDir: .
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        value: d6e6b68cd2fb1292fc841548a4ac537b6e0266442bfb48433abbf815bc8091a7
      - key: CLIENT_URL
        fromService:
          name: car-rental-system
          type: web
          property: host
